SELECT TERM, MNEMONIC, INSTRUCTOR
FROM {{ ref('assigned') }}
WHERE (TERM, MNEMONIC) IN (
	SELECT TERM, MNEMONIC
	FROM {{ ref('assigned') }}
	GROUP BY TERM, MNEMONIC
	HAVING COUNT(DISTINCT INSTRUCTOR) > 1
)
